# Generated by Django 4.0.3 on 2022-03-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('room_pix', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_img', models.ImageField(blank=True, null=True, upload_to='room')),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
                ('amenity', models.CharField(max_length=100)),
                ('min_guest', models.IntegerField()),
                ('max_guest', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.category')),
            ],
        ),
    ]
