# Generated by Django 4.0.3 on 2022-03-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tag',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.category'),
        ),
    ]
