# Generated by Django 4.0.3 on 2022-03-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_category_slug_room_available_room_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True, 'verbose_name': 'Room', 'verbose_name_plural': 'Room'},
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
