# Generated by Django 4.0.3 on 2022-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deluxe_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='luxury_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='royal_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='standard_suite',
            field=models.BooleanField(default=False),
        ),
    ]
