# Generated by Django 4.0.3 on 2022-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_deluxe_suite_room_luxury_suite_room_royal_suite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deluxe_suite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='luxury_suite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='royal_suite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='standard_suite',
            field=models.BooleanField(default=True),
        ),
    ]
