# Generated by Django 4.0.3 on 2022-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_deluxe_suite_alter_room_luxury_suite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deluxe_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='luxury_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='royal_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='standard_suite',
            field=models.BooleanField(default=False),
        ),
    ]
