# Generated by Django 4.0.3 on 2022-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_payment_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_upadate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_code',
            field=models.CharField(max_length=50),
        ),
    ]
