# Generated by Django 4.0.3 on 2022-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='future',
            field=models.BooleanField(default=False),
        ),
    ]
