# Generated by Django 4.0.3 on 2022-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('carousel', models.ImageField(blank=True, null=True, upload_to='carousel')),
                ('carousel2', models.ImageField(blank=True, null=True, upload_to='carousel')),
                ('carousel3', models.ImageField(blank=True, null=True, upload_to='carousel')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('mobile', models.CharField(max_length=20)),
                ('mobile2', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('about', models.TextField()),
                ('about2', models.TextField()),
                ('contact', models.TextField()),
                ('copyright_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TalkToUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
