# Generated by Django 4.0.3 on 2022-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_companyprofile_options_alter_talktous_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='carousel4',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
    ]
